server:
  port: 8088
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/siga?serverTimezone=America/Santiago&useSSL=false
    username: servoclay@gmail.com
    password: jIq2atp81QIh

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG