server:
  port: 8089
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/siga?serverTimezone=America/Santiago&useSSL=false
    username: root
    password: 

logging:
  file: logs/sga-api.log
  level:
    org:
      hibernate:
        SQL: DEBUG
